package so;

import javax.swing.*;
import java.util.*;
import Beans.*;

/**
 * @author Mateus
 */
public class LTG extends JPanel {

	Collection<Processo> AptoProcessoLista = new ArrayList<>();
	Collection<Processo> ExeProcessoLista = new ArrayList<>();

	public LTG() {
		// TODO - implement LTG.LTG
		throw new UnsupportedOperationException();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	private void initComponents() {
		// TODO - implement LTG.initComponents
		throw new UnsupportedOperationException();
	}

}