package so;

import java.util.*;
import Beans.*;

/**
 * @author Mateus
 */
public class SJF extends RoundRobin {

	/**
	 * Variables declaration - do not modify
	 */
	public javax.swing.JPanel Apto;
	public javax.swing.JPanel AptoPai;
	public javax.swing.JComboBox<String> AptosLista;
	public javax.swing.JPanel Exe;
	public javax.swing.JComboBox<String> ExeLista;
	public javax.swing.JPanel ExePai;
	/**
	 * Creates new form SJF
	 */
	Collection<Processo> AptoProcessoLista = new ArrayList<>();
	Collection<Processo> ExeProcessoLista = new ArrayList<>();

	public SJF() {
		// TODO - implement SJF.SJF
		throw new UnsupportedOperationException();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	private void initComponents() {
		// TODO - implement SJF.initComponents
		throw new UnsupportedOperationException();
	}

	/**
	 * </editor-fold>
	 * @param evt
	 */
	private void AptosListaActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO - implement SJF.AptosListaActionPerformed
		throw new UnsupportedOperationException();
	}

	/**
	 * 
	 * @param evt
	 */
	private void ExeListaActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO - implement SJF.ExeListaActionPerformed
		throw new UnsupportedOperationException();
	}

}